SELECT 
T.DAYS,
T.AVERAGE_TEMPERATURE,
T.AVERAGE_RAIN,
TR.DAYS,
TR.HOURS,
TR.VEHICLE_COUNT,
TR.AVERAGE_SPEED,
TR.CONGESTION_LEVEL,
TR.WEATHER_CONDITION,
TR.TRAFFIC_RULE_VIOLATION
FROM TEMPERATURE T 
JOIN TRAFFIC TR
ON T.DAYS=TR.DAYS;  

SELECT TR.DAYS
AVG(TR.VEHICLE_COUNT) AS V_CO
FROM TEMPERATURE T 
JOIN TRAFFIC TR
ON T.DAYS=TR.DAYS;

SELECT TR.HOURS,
AVG(AVERAGE_SPEED) AS AVG_SPEED
FROM TEMPERATURE T 
JOIN TRAFFIC TR
ON T.DAYS=TR.DAYS
GROUP BY TR.HOURS
ORDER BY TR.HOURS;

SELECT TR.TRAFFIC_RULE_VIOLATION,
COUNT(*) AS TOTAL_COUNT
FROM TRAFFIC TR
GROUP BY TR.TRAFFIC_RULE_VIOLATION
ORDER BY TOTAL_COUNT
DESC LIMIT 1;

SELECT TR.CONGESTION_LEVEL,
AVG(T.AVERAGE_TEMPERATURE) AS AVG_TEMP
FROM TEMPERATURE T 
JOIN TRAFFIC TR
ON T.DAYS=TR.DAYS
GROUP BY TR.CONGESTION_LEVEL
ORDER BY TR.CONGESTION_LEVEL

SELECT 
CASE
WHEN TR.WEATHER_CONDITION='Rainy' THEN 'RAINY'
ELSE 'NON-RAINY'
END AS 'RAIN CATEGORY',
TR.CONGESTION_LEVEL,
COUNT(*) 
FROM TRAFFIC TR
ORDER BY RAIN CATEGORY 




