SELECT 
T.DAYS,
T.AVERAGE_TEMPERATURE,
T.AVERAGE_RAIN,
TR.DAYS,
TR.HOURS,
TR.VEHICLE_COUNT,
TR.AVERAGE_SPEED,
TR.CONGESTION_LEVEL,
TR.WEATHER_CONDITION,
TR.TRAFFIC_RULE_VIOLATION
FROM TEMPERATURE T 
JOIN TRAFFIC TR
ON T.DAYS=TR.DAYS;  

--QUESTION 1:What is the average vehicle count for each day?
SELECT TR.DAYS,
AVG(TR.VEHICLE_COUNT) AS V_COUNT
FROM TEMPERATURE T 
JOIN TRAFFIC TR
ON T.DAYS=TR.DAYS
GROUP BY TR.DAYS
ORDER BY TR.DAYS;

--QUESTION 2:What is the average speed for each hour?
SELECT TR.HOURS,
AVG(AVERAGE_SPEED) AS AVG_SPEED
FROM TEMPERATURE T 
JOIN TRAFFIC TR
ON T.DAYS=TR.DAYS
GROUP BY TR.HOURS
ORDER BY TR.HOURS;

--QUESTION 3:How many records are there for each congestion level?
SELECT  TR.CONGESTION_LEVEL,
COUNT(*) AS TOTAL_RECORDS
FROM TRAFFIC TR
GROUP BY  TR.CONGESTION_LEVEL;

--QUESTION 4:What are the different weather conditions present in the dataset?
SELECT DISTINCT TR.WEATHER_CONDITION
FROM TRAFFIC TR;

--QUESTION 5:What is the average vehicle count during rainy vs non-rainy days?
SELECT CASE
WHEN TR.WEATHER_CONDITION='Rainy' THEN 'RAINY'
ELSE 'NON-RAINY'
END AS RAIN_CATEGORY,
AVG(TR.VEHICLE_COUNT)
FROM TRAFFIC TR
GROUP BY RAIN_CATEGORY ;

--QUESTION 6:Which hour has the highest average traffic (vehicle count)?
SELECT TR.HOURS,
AVG(TR.VEHICLE_COUNT) AS AVG_TRAFFIC
FROM TRAFFIC TR
GROUP BY TR.HOURS
ORDER BY AVG_TRAFFIC DESC 
LIMIT 1;
--QUESTION 7:What is the average speed for each congestion level?
SELECT TR.CONGESTION_LEVEL,
AVG(TR.AVERAGE_SPEED) 
FROM TRAFFIC TR
GROUP BY TR.CONGESTION_LEVEL;

