SELECT 
T.DAYS,
T.AVERAGE_TEMPERATURE,
T.AVERAGE_RAIN,
TR.DAYS,
TR.HOURS,
TR.VEHICLE_COUNT,
TR.AVERAGE_SPEED,
TR.CONGESTION_LEVEL,
TR.WEATHER_CONDITION,
TR.TRAFFIC_RULE_VIOLATION
FROM TEMPERATURE T 
JOIN TRAFFIC TR
ON T.DAYS=TR.DAYS;  

--QUESTION 1:Which hour has the highest average traffic (vehicle count)?
SELECT TR.DAYS
AVG(TR.VEHICLE_COUNT) AS V_CO
FROM TEMPERATURE T 
JOIN TRAFFIC TR
ON T.DAYS=TR.DAYS;

--QUESTION 2:What is the average speed for each congestion level?
SELECT TR.HOURS,
AVG(AVERAGE_SPEED) AS AVG_SPEED
FROM TEMPERATURE T 
JOIN TRAFFIC TR
ON T.DAYS=TR.DAYS
GROUP BY TR.HOURS
ORDER BY TR.HOURS;

--QUESTION 3:Which traffic violation type occurs the most?
SELECT TR.TRAFFIC_RULE_VIOLATION,
COUNT(*) AS TOTAL_COUNT
FROM TRAFFIC TR
GROUP BY TR.TRAFFIC_RULE_VIOLATION
ORDER BY TOTAL_COUNT
DESC LIMIT 1;

--QUESTION 4:What is the average temperature for each congestion level?
SELECT TR.CONGESTION_LEVEL,
AVG(T.AVERAGE_TEMPERATURE) AS AVG_TEMP
FROM TEMPERATURE T 
JOIN TRAFFIC TR
ON T.DAYS=TR.DAYS
GROUP BY TR.CONGESTION_LEVEL
ORDER BY TR.CONGESTION_LEVEL;

--QUESTION 5:How does rain affect congestion level distribution?
SELECT 
CASE
WHEN TR.WEATHER_CONDITION='Rainy' THEN 'RAINY'
ELSE 'NON-RAINY'
END AS RAIN_CATEGORY,
TR.CONGESTION_LEVEL,
COUNT(*) AS CONGESTION_COUNT
FROM TRAFFIC TR
GROUP BY RAIN_CATEGORY,TR.CONGESTION_LEVEL
ORDER BY RAIN_CATEGORY,TR.CONGESTION_LEVEL;

--QUESTION 6:Which day has the highest traffic volume?
SELECT TR.DAYS,
COUNT(*) AS TRAFFIC_VOLUME
FROM TRAFFIC TR
GROUP BY TR.DAYS
ORDER BY TRAFFIC_VOLUME DESC
LIMIT 1;

--QUESTION 7:	What is the relationship between precipitation and vehicle count?
SELECT T.AVERAGE_RAIN,
AVG(TR.VEHICLE_COUNT) AS AVG_VEHICLE_COUNT
FROM TEMPERATURE T 
JOIN TRAFFIC TR
ON T.DAYS=TR.DAYS
GROUP BY T.AVERAGE_RAIN
ORDER BY T.AVERAGE_RAIN;

--QUESTION 8:During which hours does high congestion mostly occur?
SELECT
TR.HOURS,COUNT(*) AS HIGH_CONGESTION
FROM TRAFFIC TR
WHERE TR.CONGESTION_LEVEL='High'
GROUP BY TR.HOURS
ORDER BY HIGH_CONGESTION DESC
LIMIT 1;

--QUESTION 9:Which weather condition leads to the lowest average speed?
SELECT TR.WEATHER_CONDITION,
AVG(TR.AVERAGE_SPEED) AS AVG_SPEED
FROM TRAFFIC TR
GROUP BY TR.WEATHER_CONDITION
ORDER BY AVG_SPEED ASC
LIMIT 1;

--QUESTION 10:What is the top traffic violation during high congestion periods?
SELECT TR.TRAFFIC_RULE_VIOLATION,
COUNT(*) AS TRAFFIC_VIOLATION_COUNT
FROM TRAFFIC TR
WHERE TR.CONGESTION_LEVEL='High'
GROUP BY TR.TRAFFIC_RULE_VIOLATION
ORDER BY  TRAFFIC_VIOLATION_COUNT DESC
LIMIT 1;

--QUESTION 1:Does rain increase traffic congestion?
SELECT CASE
WHEN  TR.WEATHER_CONDITION='Rainy' THEN 'RAINY'
ELSE 'NON-RAINY'
END AS RAIN_CATEGORY,
TR.CONGESTION_LEVEL,
COUNT(*) AS CONGESTION_COUNT 
FROM TRAFFIC TR
GROUP BY RAIN_CATEGORY,TR.CONGESTION_LEVEL
ORDER BY RAIN_CATEGORY,CONGESTION_COUNT DESC;

--QUESTION 2:Does temperature impact vehicle speed?
SELECT T.AVERAGE_TEMPERATURE,
AVG(TR.AVERAGE_SPEED) AS AVG_SPEED
FROM TEMPERATURE T 
JOIN TRAFFIC TR
ON T.DAYS=TR.DAYS
GROUP BY T.AVERAGE_TEMPERATURE
ORDER BY AVG_SPEED DESC;


SELECT 
 CASE 
  WHEN T.AVERAGE_TEMPERATURE< 15 THEN 'LOW TEMP'
  WHEN T.AVERAGE_TEMPERATURE BETWEEN 15 AND 25 THEN 'MEDIUM TEMP'
  ELSE 'HIGH TEMP'
 END AS TEMP_CATEGORY,
AVG(TR.AVERAGE_SPEED) AS AVG_SPEED
FROM TEMPERATURE T 
JOIN TRAFFIC TR
ON T.DAYS=TR.DAYS
GROUP BY TEMP_CATEGORY
ORDER BY AVG_SPEED DESC;
  

--QUESTION 3:What is the peak traffic pattern across the day?
SELECT TR.HOURS,
TR.CONGESTION_LEVEL,
COUNT(*) AS TRAFFIC_COUNT
FROM TRAFFIC TR
GROUP BY TR.HOURS,TR.CONGESTION_LEVEL
ORDER BY TR.HOURS,TRAFFIC_COUNT DESC;

--QUESTION 4:How do traffic violations vary with congestion level?
SELECT TR.CONGESTION_LEVEL,
TR.TRAFFIC_RULE_VIOLATION,
COUNT(*) AS COUNT_VIOLATION 
FROM TRAFFIC TR
GROUP BY TR.CONGESTION_LEVEL,TR.TRAFFIC_RULE_VIOLATION
ORDER BY COUNT_VIOLATION DESC;  

--QUESTION 5:Can you identify high-risk conditions (weather + congestion + violations)?
SELECT 
TR.WEATHER_CONDITION,
TR.TRAFFIC_RULE_VIOLATION,
COUNT(*) AS RISK_COUNT
FROM TRAFFIC TR
WHERE TR.CONGESTION_LEVEL='High'
GROUP BY TR.WEATHER_CONDITION,TR.TRAFFIC_RULE_VIOLATION
ORDER BY RISK_COUNT DESC;


